id: P010530
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG5397
  title: བྱ་མགྲིན་སྔོན་ཟླ་བའི་རྟོགས་བརྗོད་
  author: ''
  volumes:
    ed061a443ebb409e954d4f042a2a2510:
      image_group_id: I1KG5413
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
