id: I95313F2D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:39:19+00:00'
last_modified: '2022-06-08T14:17:10.088501+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5397
  title: བྱ་མགྲིན་སྔོན་ཟླ་བའི་རྟོགས་བརྗོད་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7150':
      image_group_id: I1KG5413
      title: ''
      total_pages: 276
      order: 1
      base_file: 7150.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
